title: rootkit.es
description: rootkit.es
baseurl: ""
theme: just-the-docs

url: https://rootkit.es

include:
  - "images"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/therealdreg/rootkitweb" 
gh_edit_branch: "main" 
gh_edit_view_mode: "tree"


#aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template

permalink: pretty

logo: "/assets/images/pylori_logo.png"

nav_external_links:
  - title: buzzpirat
    url: https://buzzpirat.com/
  - title: github
    url: https://github.com/therealdreg/

footer_content: "<a href=\"https://www.rootkit.es\">rootkit.es</a>"
